name: Claude Code Integration

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [opened, synchronize]

jobs:
  claude:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '@claude') || github.event_name == 'issues'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          pip install pytest pytest-cov vulture ruff
          npm install -g eslint
          
      - name: Run Claude Code Action
        uses: anthropics/claude-code-action@v1
        with:
          claude-api-key: ${{ secrets.CLAUDE_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
  quality-checks:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install test dependencies
        run: |
          pip install pytest pytest-cov vulture ruff
          
      - name: Run TDD compliance check
        run: |
          # 基本的なTDDコンプライアンスチェック
          if [ -n "$(git diff --name-only HEAD~1 | grep -E '\.(py|js|ts)$' | grep -v test)" ]; then
            if [ -z "$(git diff --name-only HEAD~1 | grep test)" ]; then
              echo "Error: Implementation changes without test changes detected"
              exit 1
            fi
          fi
          
      - name: Run unused code detection
        run: |
          # Python未使用コード検出
          find . -name "*.py" -not -path "./test*" -exec vulture {} \;
          
      - name: Check test coverage
        run: |
          # カバレッジチェック（プロジェクトが存在する場合のみ）
          if [ -f "requirements.txt" ] || [ -f "pyproject.toml" ]; then
            pytest --cov=. --cov-fail-under=60 || true
          fi